on: [pull_request]
name: Check PR for issues
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdownlint
      uses: prologic/action-markdownlint@v0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-check
        level: warning
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
