on: [pull_request]
name: Check PR for issues
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: xt0rted/markdownlint-problem-matcher@v1
    - run: markdownlint **/*.md --ignore node_modules
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
