on: [pull_request]
name: Check PR for issues
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        $problemMatcher = Resolve-Path (Join-Path ".github" "problem-matchers" "markdownlint.json");
        Write-Host "Adding matcher $problemMatcher...";
        Write-Host "::add-matcher::$problemMatcher";
      shell: pwsh
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
